## Generates the last plot
## Assuming the household_power_consumption.txt data is in the same directory as this script

## Start and end dates for analysis, inclusive
start_date <- as.Date("2007-02-01")
end_date <- as.Date("2007-02-02")


## Loads required data for household power consumption between 2007-02-01 and 2007-02-02
dat <- read.table("household_power_consumption.txt", sep = ";", header=TRUE)

## Converts Date and Time vars to Date/POSIXct data types, for plotting
## Subsetting before the time-intensive time conversion
dat$Date <- as.Date(dat$Date, "%d/%m/%Y")
dat <- dat[dat$Date>=start_date & dat$Date<=end_date, ]
dat$Time <- as.POSIXct(strptime(paste(dat$Date,dat$Time),format ="%Y-%m-%d %H:%M:%S"))


## Makes all data after Time in dat numeric, we'll be plotting most of it
for (x in 3:length(dat)){
    dat[, x]<-as.numeric(dat[, x])
}


## Generates plot and save into plot4.png
png(file="plot4.png",width = 480, height = 480)

## Sets plot dimensions
par(mfcol=c(2,2))

## Plot (1, 1): plot generated by plot2.R
with(dat, plot(Time, Global_active_power, type="l", xlab="", ylab="Global Active Power"))

## Plot (2, 1): plot generated by plot3.R
plot(dat$Time,dat$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(dat$Time,dat$Sub_metering_2, col="red")
lines(dat$Time,dat$Sub_metering_3, col="blue")
legend("topright", lty=c(1,1,1), col=c("black","red","blue"), 
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n")

## Plot (1, 2): new plot of voltage
with(dat, plot(Time, Voltage, type="l", xlab="datetime"))

## Plot (2, 2): new plot of Global reactive power
with(dat, plot(Time, Global_reactive_power, type="l", xlab="datetime"))

dev.off()
